#!/bin/bash

# Comment out if you dont want the option to be loaded..

# OS specific configs + small diffs like the way colors works
case $os in
     "Linux")
        true
        ;;
     "Darwin")
        true
        ;;
esac

##
# Misc settings
##
editor='nano' # Your favorite editor, will be set in 'loader' if set
colormode='bash' # What should create our colors, 'tput' or 'bash'.
                 # Tput is the "new" way of doing colors, but is a
                 # little  buggy some times.. Anything else disables colors

#startup_debug=1 # Outputs extra information at the start of a new shell

[ ${startup_debug} ] && echo "ninjab debug mode enabled" ||:
[ ${startup_debug} ] && echo "Asuming os is ${os}" ||:

#load_global_bashrc=1		# Try to load /etc/bashrc
load_global_bash_completion=1	# Try to load /etc/bash_completion, /opt/local/etc/bash_completion or brew bash completion on osx (port install bash-completion) (can delay startup of new shells by seconds!) But fast when the files are cached in memory

# If you want to be asked to load ninjab. Create a file in /etc/ninjab_ask or ~/.ninjab_ask
# and fill out this optional question (will be "do you want to load more usefull bash configurations?" as default)
#ninjab_ask_text="Are you sure you want to load a custom bashrc?"

#---------------------------------------------------------------------
# Parts
#
# Sub_options of parts wont get loaded if you comment out the main part itself..
#---------------------------------------------------------------------

########################################
# parts/1_bash
#
# Bash tweeks
########################################
load_part_bash=1
load_part_bash_completions=1
load_part_bash_completions_sshHostUseConfig=1 # Try to use ~/.ssh/config to complete ssh completion instead of hostfile
load_part_bash_misccolors=1 # Enable colors on example man pages.
#
load_part_bash_history=1 # Timestamp in history, ignore dupes
#load_part_bash_history_max=3000 # This is set to 2000 if not defined
#load_part_bash_history_ignoreCommon=1 # Ignore common typed commands (like ls, fg, bg, ps aux)

load_part_bash_hotkeys=1 # Create some hotkeys, see documentation for what.
#load_part_bash_tweek_hotkeys=1 # Tweek some default bash hotkeys behavior. Eg turns on cycling TAB completion

########################################
# parts/2_oneliners
########################################
#load_part_oneliners=1


########################################
# parts/3_aliases
#
# Shortcuts to a more effective usage of different commands
########################################
load_part_aliases=1
load_part_aliases_oneletters=1 # Load a couple of one-letters aliases
load_part_aliases_ls=1 # More out of the default 'ls'
load_part_aliases_ls_shortcuts=1 # Load . .. ... .... aliases for pwd, cd .., cd ../.. and so on..
load_part_aliases_same=1 # To get common enhancements for some commands, like rm will be 'rm -v -i', comment out to deny self aliasing.


########################################
# parts/4_prompt
#
# A more usefull bash prompt
########################################
load_part_prompt=1
#load_part_prompt_notifyDaychange=1
#load_part_prompt_dontset_titlebar=1 # Dont change the titlebar to match path
#
# Set static info at the beginning of the bash prompt. Can also be defined in /etc/sysinfo or ~/.sysinfo if system_info_check is defined,
# or you can define them here
#system_info_check=1

# system_type makes the color, crit is red, prod is yellow and test is green.
#system_type="crit" # crit|prod|test or ignore
#
# This is static text at the beginning of the prompt. Will have the color defined above if any.
# Can also be defined in /etc/sysinfo or ~/.sysinfo
#system_category="webserver"

# Show runtime of last command if it took more than X seconds, comment out to disable
load_part_prompt_slowcommandwarn=10

# Set to load different parts of the per folder settings.
# If the setting is not here prepended with load_part_njbcfg__... it wont get loaded.
# Example (first setting), this will enable loading of the per folder setting called
# "titlebar". If you want to set this setting, add a line like:
# "titlebar your titlebar" without the quotes to a file called
# .njbcfg in the folder you want the titlebar to change.
load_part_prompt_njbcfg_set_titlebar=1

# /etc/sysinfo or ~/.sysinfo will overwrite this settings if they are set
#load_part_prompt_njbcfg_system_type=1
#load_part_prompt_njbcfg_system_category=1

# If you want extra safety, this settings will make sure that .njbcfg
# configs are only loaded if we are the owner of the file.
#load_part_prompt_force_njbcfg_owner=1


########################################
# parts/5_stateinfo
#
# Gives you as much info as it can about the current state, folder or file.
########################################
load_part_stateinfo=1
load_part_stateinfo_alias='?' # Alias for the function which will give you current state information. If commented out, use 'stateinfo'.
load_part_stateinfo_maxlines=50 # How many lines should we accept before asking if we should display them or not, comment out for unlimited

########################################
# parts/6_pipes
#
# Holds function which can be used as pipes.
########################################
load_part_pipes=1
