#!/bin/bash

# Exit if running non-interacive
[ -z "$PS1" ] && return

mydir=$(cd $(dirname ${BASH_SOURCE:-$0});pwd)
os=$(uname -s)
bash_version=${BASH_VERSION%.*}

. ${mydir}/functions
. ${mydir}/config

if [ -f /etc/bashrc_ask -o -f ~/.bashrc_ask  ]; then
    if ! yesno --charcount 1 --default yes "${bashrc_ask_text:-"Do you want to load a more usefull bashrc?"} [Yn]"; then
	return
    fi
fi

if [ ! -z $load_global_bashrc ]; then
    if [ -f /etc/bashrc ]; then
        echo "Loading etc bashrc"
        . /etc/bashrc
    fi
fi

if [ ! -z $load_global_bash_completion ]; then
    if [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi

    if [ -f /opt/local/etc/bash_completion ]; then
	. /opt/local/etc/bash_completion
    fi
fi

for i in $mydir/parts/*; do
    # Load every file as long as they dont have a # ~ in the filename 
    if ! [[ $i =~ \#|~ ]]; then
        . $i
    fi
done
