#!/bin/bash

# Exit if running non-interacive
[ -z "$PS1" ] && return

# Make sure :)
case $- in
    *i*)    # interactive shell
	;;
    *)      # non-interactive shell
	return
	;;
esac

mydir=$(cd $(dirname ${BASH_SOURCE:-$0});pwd)
os=$(uname -s)
bash_version=${BASH_VERSION%.*}

. ${mydir}/functions
. ${mydir}/config

if [ -f /etc/bashrc_ask -o -f ~/.bashrc_ask  ]; then
    if ! yesno --charcount 1 --default yes "${bashrc_ask_text:-"Do you want to load a more usefull bashrc?"} [Yn]"; then
	return
    fi
fi

if [ ! -z $load_global_bashrc ]; then
    if [ -f /etc/bashrc ]; then
	[ ${startup_debug} ] && echo -n "Loading global /etc/bashrc"
        . /etc/bashrc
	[ ${startup_debug} ] && echo " - done"
    fi
fi

if [ ! -z $load_global_bash_completion ]; then
    if [ -f /etc/bash_completion ]; then
	[ ${startup_debug} ] && echo -n "Loading global /etc/bash_completion"
        . /etc/bash_completion
	[ ${startup_debug} ] && echo " - done"
    fi

    if [ -f /opt/local/etc/bash_completion ]; then
	[ ${startup_debug} ] && echo -n "Loading global /opt/local/etc/bash_completion"
	. /opt/local/etc/bash_completion
	[ ${startup_debug} ] && echo " - done"
    fi
fi

for i in $mydir/parts/*; do
    # Load every file as long as they dont have a # ~ in the filename 
    if ! [[ $i =~ \#|~ ]]; then
	[ ${startup_debug} ] && echo -en "\nPart ${i} -"
        . $i
	[ ${startup_debug} ] && echo "End of part ${i}"
    fi
done
